### PR TITLE
FIX for rails_env

### PR DESCRIPTION
**Pull request by nirdshabo**
fix for rails_env instead of stage env

### CODE REVIEW

**Comment by Funfun** [comment]
Cool, thanks!

**Comment by romikoops** [comment]
Please get on board the pull request ASAP, it is superb. I use 12 factor app. It means Rails env = production for staging. So in Capistrano v3 I have stage=staging, but rails_env=production.

**Comment by jesperronn** [comment]
:+1:  you never merged this?? I am surprised to see that this PR is so old and not merged. Is there an updated fork anybody can recommend instead until this is fixed?

**Comment by romikoops** [comment]
Looks like it is easy to support 100500 forks with this commit :(

**Comment by cmrd-senya** [comment]
Please, merge!

**Comment by jesperronn** [comment]
Update, in case somebody else face the same problem.

Since this is still not merged, I successfully updated my `Gemfile`:

```
gem 'capistrano-rails-collection', github: 'zonkeynir/capistrano-rails-collection', ref: '919929a'
```

**Comment by ianheggie** [comment]
Thanks zonkeynir - that fixed my problem as well and saved me forking it myself.

**Comment by tvdeyen** [comment]
Please merge this, as this is the correct usage for setting the rails env. The stage is a name of server, not of an rails environment. Therefore capistrano introduced the `rails_env` var.

**Comment by cmrd-senya** [comment]
I guess we must consider this gem abandonded. I launched a discussion on overtaking the ownership [here](http://help.rubygems.org/discussions/questions/9615-capistrano-rails-collection-has-been-abandonded). However I think it is as easy as releasing a gem with patches applied under a different name, like "capistrano-rails-collection-2".

**Comment by tvdeyen** [comment]
Or even better contribute and merge this into `capistrano-rails` where it belongs.

**Comment by cmrd-senya** [comment]
@dei79 gave me push access on this repository, so I was able to merge this. Thanks!

However, the issue is that we must also release the gem with the fix on the rubygems, and I have no privileges for that.

**Comment by dei79** [comment]
Send me a personal message with your mail address so that I can add you to the owners of this gem as well

**Comment by jesperronn** [comment]
Thanks @dei79 for following up! Good to see that the gem can be brought up-to-date again.

**Comment by cmrd-senya** [comment]
Fixed version has been released as 0.1.0. Thanks @dei79 again!

**Pull request merged**
